### ISSUE TITLE
ERROR:Task exception was never retrieved

### ISSUE THREAD

**Issue by SashaCanfield03** [Synthintel0/MyGirlGPT#14]
Every time I try to do something in the gui, I get this error:

INFO:HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
ERROR:Task exception was never retrieved
future: <Task finished name='y5mh04db7uq_90' coro=<Queue.process_events() done, defined at /home/jet_mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 90, 'data': ...on_hash': 'y5mh04db7uq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing>
Traceback (most recent call last):
  File "/home/jet_mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/jet_mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/jet_mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/jet_mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 90, 'data': ...on_hash': 'y5mh04db7uq'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
INFO:HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"

I've tried fixing it for a while, but I'm not sure what the problem is. It seems to be a problem with the gui, not a problem with the LLM. I tried running it in CPU mode too, and it has the same problem

**Comment by Synthintel0** [comment]
The project wants to call stable diffusion api ([http://localhost:7860/](http://localhost:7860/reset)) to create pic. But it didn't get the return. To make sure you have setup the stable diffusion webui with api argument.
